name: Android Deploy to Play Store

on:
  push:
    branches:
      - 'main'

jobs:
  Android-Deploy:
    runs-on: ubuntu-latest
    
    env:
      IONIC_TOKEN: ${{ secrets.IONIC_TOKEN }}
      APP_ID: '161d2d34'
      SIGNING_CERT: 'production'
      DESTINATION: 'Play Store'
   
    steps:
    - name: Install Ionic Cloud CLI
      run: curl -sL https://ionic.io/get-ionic-cloud-cli | bash   
   
    - name: Build AAB and Save Android Build ID
      id: android_build
      run: |
        ANDROID_BUILD_ID=$(ionic-cloud build android release --app-id=$APP_ID --commit=$GITHUB_SHA --signing-cert=$SIGNING_CERT  --aab-name=app.aab --json --token=$IONIC_TOKEN | jq -r ".buildId")
        echo "ANDROID_BUILD_ID=$ANDROID_BUILD_ID" >> $GITHUB_OUTPUT
  
    - name: Upload AAB
      uses: actions/upload-artifact@v3
      with:
        name: Signed AAB
        path: ./app.aab
          
    - name: Deploy to Play Store
      run: ionic-cloud deploy android --app-id=$APP_ID --build-id=${{ steps.android_build.outputs.ANDROID_BUILD_ID }} --destination=$DESTINATION --token=$IONIC_TOKEN
